order_list:
   path: /api/v1/orders
   controller: App\Controller\OrderController::index
   methods: [GET]
order_create:
   path: /api/v1/orders
   controller: App\Controller\OrderController::create
   methods: [POST]
order_home:
  path: /
  controller: App\Controller\HomeController::index
  methods: [GET, POST]
cancel_order:
  path: /order/{id}/state/{state}
  controller: App\Controller\HomeController::cancelOrder
  methods: [GET]
picker:
  path: /picker
  controller: App\Controller\PickerController::index
  methods: [GET, POST]
picker_view_order:
  path: /picker/order/{id}
  controller: App\Controller\PickerController::getOrder
  methods: [GET]
picker_state_change:
  path: /picker/order/{id}/state/{state}
  controller: App\Controller\PickerController::changeState
  methods: [GET]
shipper:
  path: /shipper
  controller: App\Controller\ShipperController::index
  methods: [GET, POST]
shipper_view_order:
  path: /shipper/order/{id}
  controller: App\Controller\ShipperController::getOrder
  methods: [GET]
shipper_state_change:
  path: /shipper/order/{id}/state/{state}
  controller: App\Controller\ShipperController::changeState
  methods: [GET]
manager:
  path: /manager
  controller: App\Controller\ManagerController::index
  methods: [GET, POST]
manager_view_order:
  path: /manager/order/{id}
  controller: App\Controller\ManagerController::getOrder
  methods: [GET]